### ISSUE TITLE
Device manager node stomps over whole msg

### ISSUE THREAD

**Issue by philippe-gregoire** [ibm-watson-iot/node-red-contrib-ibm-wiotp-device-ops#6]
The Device manager node replaces the whole msg, not only the msg.payload.
So, when trying to use it for example to fulfill a HTTP request to list devices, you lose the msg.req and msg.res, so the response cannot be sent (and there's no good way to stash it elsewhere)

**Comment by philippe-gregoire** [comment]
I think the issue is in nodes/device_manager.js around line 120 (and 129):
`var onSuccess = function(argument) {
                  var msg = {
                    payload : argument
}`
why not just 
`msg.payload=argument`
?

**Comment by jeffdare** [comment]
Fixed by #10
